image: node:8-alpine

variables:
  PUBLISH_PATH: 'dist/'

services:
  - mongo:latest

stages:
  - buildThenTest
  - release

buildThenTest:
  stage: buildThenTest
  artifacts:
    name: 'nmdb-${CI_COMMIT_SHA}'
    paths:
      - ${PUBLISH_PATH}
  script:
    - yarn
    - yarn run build
    - yarn run test

release:
  stage: release
  script:
    - cd ${PUBLISH_PATH}
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
    - npm publish
  only:
    - tags
